language: node_js
node_js:
  - "0.10"

branch:
  only:
    - master

before_script:
  - npm install --quiet -g grunt-cli bower
  - npm install
  - bower install

script:
  - grunt test
  - grunt build